Animal.Web/Controllers/AccountApiController.cs
using System.Web.Http;
using Animal.Bal.Interfaces;
using Animal.Common.Models.Bal;

namespace Animal.Web.Controllers
{

	public class AccountApiController : ApiController
	{
		private readonly IAccountValidationService _accountValidationService;
		private readonly IUserService _userService;

		public AccountApiController(IAccountValidationService accountValidationService, IUserService userService)
		{
			_accountValidationService = accountValidationService;
			_userService = userService;
		}

		public bool Register(UserModel model)
		{
			if (ModelState.IsValid)
			{
				var isEmailAlreadyExists = _accountValidationService.IsEmailAlreadyExists(model.Email);
				if (isEmailAlreadyExists)
				{
					ModelState.AddModelError("Email", "Email already registered");
				}

				return true;
			}

			return false;
		}

		public bool Login(LoginModel model)
		{
			return  _userService.LoginUser(model);			
		}
	}
}

Animal.Web/Controllers/AccountController.cs
using System;
using System.Web.Mvc;
using System.Web.Security;
using Animal.Bal.Interfaces;
using Animal.Common.Models.Bal;

//using System.ComponentModel.DataAnnotations;
//using Microsoft.AspNet.Identity.EntityFramework;

namespace Animal.Web.Controllers
{
	public class AccountController : Controller
	{
		private readonly IAccountValidationService _accountValidationService;
		private readonly IUserService _userService;

		public AccountController(IUserService userService, IAccountValidationService accountValidationService)
		{
			_userService = userService;
			_accountValidationService = accountValidationService;
		}

		[HttpGet]
		public ActionResult GetRegistrationView()
		{
			var model = new UserModel();
			return View("Registration", model);
		}


		[HttpPost]
		public ActionResult Register(UserModel model)
		{
			if (ModelState.IsValid)
			{
				var isEmailAlreadyExists = _accountValidationService.IsEmailAlreadyExists(model.Email);
				if (isEmailAlreadyExists)
				{
					ModelState.AddModelError("Email", "Email already registered");
					return View("Registration", model);
				}
				_userService.AddUser(model);

				return View("RegistrationCompleted");
			}

			return View("Registration", model);
		}


		[HttpGet]
		public ActionResult GetAuthorizationView()
		{
			var model = new LoginModel();
			return View("Authorization", model);
		}


		[HttpPost]
		public ActionResult Authorization(LoginModel model)
		{
			if (ModelState.IsValid)
			{
				var loginResult = _userService.LoginUser(model);
				if (!loginResult)
				{
					ModelState.AddModelError("Email", "Invalid email or password");
					return View("Authorization", model);
				}
				else
				{
					FormsAuthentication.SetAuthCookie(model.Email, true);
					return RedirectToAction("Index", "Home");
				}
			}

			return View("Authorization", model);

		}

		[HttpGet]
		public ActionResult Logout()
		{
			Session.Clear();
			
			FormsAuthentication.SignOut();
			return RedirectToAction("Index", "Home");
		}


	//	[HttpPost]
	//	public ActionResult DeletingUser()
	//	{
		
			//var model = 
			//return View("UserWasDeleted", model)
	//	}

		[HttpGet]
		public ActionResult OwnCabView()
		{
			return View("OwnCab");
		}

		[HttpGet]
		public ActionResult RedirectToRegistration()
		{
			return View("Registration");
		}


	}
}

Animal.Web/Controllers/AnimalParticularController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Animal.Bal.Interfaces;
using Animal.Common.Models.Bal;

namespace Animal.Web.Controllers
{
	public class AnimalParticularController : Controller
	{
		private readonly IParticularAnimalService _animalParticularService;
		private readonly IKindOfAnimalService _kindOfAnimalService;
		public AnimalParticularController(IParticularAnimalService animalParticularService, IKindOfAnimalService kindOfAnimalService)
		{
			_animalParticularService = animalParticularService;
			_kindOfAnimalService = kindOfAnimalService;
		}

		
		[HttpGet]
		public ActionResult GetAnimalParticularAddingView()
		{
			var model = new AnimalPaticularEditModel
			{
				AnimalTypes = _kindOfAnimalService.GetAnimalKinds().Select(_ => new SelectListItem()
				{
					 Text = _.Name,
					Value = _.Id.ToString()
				}).ToList()
			};

			return View("AddingNewParticularAnimal", model);
		}		

		[HttpPost]
		public ActionResult AddNewAnimalParticular(AnimalParticularModel model)
		{
			if (ModelState.IsValid)
			{
				_animalParticularService.AddAnimalParticular(model);

				//return View("DifferentAnimalsFromKindList");
				return RedirectToAction("GetByAnimalType", new {id = model.AnimalTypeId});
			}
			else
			{
				var m1 = new AnimalPaticularEditModel
				{
					AnimalTypes = _kindOfAnimalService.GetAnimalKinds().Select(_ => new SelectListItem()
					{
						Text = _.Name,
						Value = _.Id.ToString()
					}).ToList()
				};

				return View("AddingNewParticularAnimal", m1);
			}

		}

		[HttpGet]
		public ActionResult GetByAnimalType(int id)
		{
			var animals = _animalParticularService.GetParticularAnimalByKindId(id);
			return View("DifferentAnimalsFromKindList", animals);
		}

		[HttpPost]
		public ActionResult Update()
		{
			return View("UpdateAnimalsParticular");
		}

		[HttpPost]
		public ActionResult DeleteParticular(int id)
		{
			return View("DifferentAnimalsFromKindList");
		}


		[HttpGet]
		public ActionResult UpdateInformationAboutAnimal()
		{
			return View("UpdateAnimalsParticular");
		}		
	}
}

Animal.Web/Controllers/AnimalTypeController.cs
using System;
using System.Web.Mvc;
using Animal.Bal.Interfaces;
using Animal.Common.Models.Bal;
using Animal.Common.Models.Data;

namespace Animal.Web.Controllers
{
	public class AnimalTypeController : Controller
	{
		private readonly IKindOfAnimalService _animalKindService;

		public AnimalTypeController(IKindOfAnimalService animalKindService)
		{
			_animalKindService = animalKindService;
		}

		[HttpGet]
		public ActionResult GetExistingAnimalKind()
		{
			var models = _animalKindService.GetAnimalKinds();
			return View("DifferentKindsOfAnimalsList", models);
		}
		[HttpPost]
		public ActionResult AddNewAnimalKind(AnimalKindModel model)
		{
			if (ModelState.IsValid)
			{
				_animalKindService.AddOrUpdateAnimalKind(model);
				return View("DifferentKindsOfAnimalsList");
			}
			else
			{
				return View("AddingNewKindOfAnimal");
			}
		}

		[HttpGet]
		public ActionResult GetAnimalKindAddingView()
		{
			var model = new AnimalKindModel();
			return View("AddingNewKindOfAnimal", model);
		}

		[HttpGet]
		public ActionResult ListOfKindsView()
		{
			var animalKinds = _animalKindService.GetAnimalKinds();
			return View("DifferentKindsOfAnimalsList", animalKinds);
		}

		[HttpGet]
		public ActionResult GetUpdateAnimalKind()
		{
			var animalKindEntity = new AnimalKindEntity();
			return View("UpdateInformationAboutKind", animalKindEntity);
		}

		[HttpPost]
		public ActionResult UpdateAnimalKind(int animalKind)
		{
			return View("UpdateInformationAboutKind");
		}



		//[HttpGet]
		//public ActionResult GetAnimalKind(int animalKindId)
		//{
		//	var model = _animalKindService.GetAnimalKindById(animalKindId);
		//	return View("AddingNewKindOfAnimal", model);
		//}



		[HttpPost]
		public ActionResult DeleteKind(AnimalKindModel model)
		{
			_animalKindService.DeleteAnimalKind(model);
			return View("DifferentKindsOfAnimalsList");
		}

	}
}

Animal.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Animal.Bal.Interfaces;
using Animal.Common.Models.Data;

namespace Animal.Web.Controllers
{
	public class HomeController : Controller
	{		
	   public ActionResult Index()
		{
			return View();
		}

		public ActionResult About()
		{
			return View("About");
		}
	}
}

Animal.Web/Controllers/NewsBoardController.cs
using System.Web.Mvc;
using Animal.Common.Models.Bal;
using Animal.Bal.Interfaces;
using Animal.Common.Models.Data;

namespace Animal.Web.Controllers
{
	public class NewsBoardController:Controller
	{
		private readonly INewsService _newsService;
		public NewsBoardController(INewsService newsService)
		{
			_newsService = newsService;
		}

		public ActionResult Index()
		{
			return View();
		}

		[HttpGet]
		public ActionResult GetNewsBoardPageView()
		{
			var model = _newsService.GetNews();
			return View("NewsBoardPage", model);
		}


		[HttpGet]
		public ActionResult GetAddNews()
		{
			var newsBoardEntity = new ParticularNewsIntoBoardEntity();
			return View("NewsBoardPage", newsBoardEntity);
		}



		[HttpPost]
		public ActionResult AddNews(ParticularNewsModel model)
		{
			if(ModelState.IsValid)
			{
				_newsService.AddNews(model);
				return View("NewsBoardPage");
			}
			else
			{
				return View("AddNews");
			}
		}
	}
}

Animal.Web/Views/AnimalParticular/AddingNewParticularAnimal.cshtml
@{
    ViewBag.Title = "AddingNewAnimalParticular";
@model Animal.Common.Models.Bal.AnimalPaticularEditModel

    }

<div class ="form-text">
<h2>Here you can add particular animal</h2>

@using (Html.BeginForm("AddNewAnimalParticular", "AnimalParticular", "Post"))
{
<div class="change-form">


    @Html.LabelFor(x => x.AnimalTypes)


    @Html.DropDownListFor(
    x => x.AnimalTypeId,
    new SelectList(Model.AnimalTypes, "Value", "Text"))


    @Html.LabelFor(x => x.HasCollar)

    @Html.TextBoxFor(x => x.HasCollar)
    @Html.ValidationMessageFor(x => x.HasCollar)

    <br>

    @Html.LabelFor(x => x.Name)

    @Html.TextBoxFor(x => x.Name)
    @Html.ValidationMessageFor(x => x.Name)

    <br>

    @Html.LabelFor(x => x.LastWeight)

    @Html.TextBoxFor(x => x.LastWeight)
    @Html.ValidationMessageFor(x => x.LastWeight)

    <br>

    @Html.LabelFor(x => x.Description)

    @Html.TextBoxFor(x => x.Description)
    @Html.ValidationMessageFor(x => x.Description)
</div>
    <button type="submit" class="btn btn-primary btn-large btn-block">Add New</button>

}
</div>

Animal.Web/Views/AnimalParticular/DifferentAnimalsFromKindList.cshtml
@{
    ViewBag.Title = "DifferentAnimalsFromKindList";
    
@model  IEnumerable<Animal.Common.Models.Bal.AnimalParticularModel>

}
    <div class ="form-text">
    <h2>Here you can see list of particular animals of this type:</h2>

@*@using (Html.BeginForm("GetAnimalParticularView", "AnimalParticular", "Get"))
{*@
        <table width="90%">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.HasCollar)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsAlive)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.HeartRhythms)
           </th>
            <th>
                @Html.DisplayNameFor(model => model.CaloriesBurned)
                </th>
            <th>
                @Html.DisplayNameFor(model => model.BreathingRate)
                </th>
            <th>
                @Html.DisplayNameFor(model => model.LastWeight)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    <label>Actions</label>
                </th>
 </tr>
                @foreach (var animalParticular in Model)
                {
                     <tr>
                    <td>
                        @Html.DisplayFor(modelItem => animalParticular.HasCollar)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => animalParticular.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => animalParticular.IsAlive)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => animalParticular.HeartRhythms)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => animalParticular.CaloriesBurned)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => animalParticular.BreathingRate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => animalParticular.LastWeight)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => animalParticular.Description)
                    </td>
                    <td>
                        @Html.ActionLink("Update", "Update", new { id = animalParticular.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = animalParticular.Id })
                    </td>
                </tr>
}
        </table>
        @Html.ActionLink("Add new animal", "GetAnimalParticularAddingView")
    </div>

Animal.Web/Views/AnimalParticular/UpdateAnimalsParticular.cshtml
@{
    ViewBag.Title = "UpdateAnimalsParticular";
    @model Animal.Common.Models.Bal.AnimalParticularModel
}
    <div class ="form-text">
<h2>Update information about animal:</h2>

@using (Html.BeginForm("UpdateInformationAboutAnimal", "AnimalParticular", "Post"))
{

<div class="change-form">
   
        @Html.LabelFor(x => x.HasCollar)
      
        @Html.TextBoxFor(x => x.HasCollar)
        @Html.ValidationMessageFor(x => x.HasCollar)
        
        <br>
    
        @Html.LabelFor(x => x.Name)
       
   
        @Html.TextBoxFor(x => x.Name)
        @Html.ValidationMessageFor(x => x.Name)
        <!-- <br>
            
          @Html.LabelFor(x => x.IsAlive)
          @Html.TextBoxFor(x => x.IsAlive)
          @Html.ValidationMessageFor(x => x.IsAlive)
          <br>
          @Html.LabelFor(x => x.HeartRhythms)
          @Html.TextBoxFor(x => x.HeartRhythms)
          @Html.ValidationMessageFor(x => x.HeartRhythms)
          <br>
          @Html.LabelFor(x => x.CaloriesBurned)
          @Html.TextBoxFor(x => x.CaloriesBurned)
          @Html.ValidationMessageFor(x => x.CaloriesBurned)
          <br>
          @Html.LabelFor(x => x.BreathingRate)
          @Html.TextBoxFor(x => x.BreathingRate)
          @Html.ValidationMessageFor(x => x.BreathingRate)
            -->
        <br>
   
        @Html.LabelFor(x => x.LastWeight)
      
        @Html.TextBoxFor(x => x.LastWeight)
        @Html.ValidationMessageFor(x => x.LastWeight)
     
        <br>
    
        @Html.LabelFor(x => x.Description)
      
        @Html.TextBoxFor(x => x.Description)
        @Html.ValidationMessageFor(x => x.Description)
       
        <button type="submit" value="btn btn-primary btn-large btn-block">Update</button>
  </div>
    }
</div>

Animal.Web/Views/AnimalType/AddingNewKindOfAnimal.cshtml
@{
    ViewBag.Title = "AddingNewKindOfAnimal";
    @model Animal.Common.Models.Bal.AnimalKindModel

}
    <div class ="form-text">
    <h2>Add new kind of animal</h2>

<h2>Here you can add new kinds of animals that you have</h2>

@using (Html.BeginForm("AddNewAnimalKind", "AnimalType", "Post"))
{
    <div class="change-form">
        <p align ="center">
        @Html.HiddenFor(_ => _.Id)

        @Html.LabelFor(x => x.Name)
            <br>
        @Html.TextBoxFor(x => x.Name)
            <br>
        @Html.ValidationMessageFor(x => x.Name)
        <br>
        @Html.LabelFor(x => x.PlannedNumberOfAnimals)
            <br>
        @Html.TextBoxFor(x => x.PlannedNumberOfAnimals)
            <br>
        @Html.ValidationMessageFor(x => x.PlannedNumberOfAnimals)
        <br>
        @Html.LabelFor(x => x.DescriptionOFAnimals)
            <br>
        @Html.TextBoxFor(x => x.DescriptionOFAnimals)
            <br>
        @Html.ValidationMessageFor(x => x.DescriptionOFAnimals)
            </p>
        <br>
        <button type="submit" class="btn btn-primary btn-large btn-block">Add new</button>
    </div>
}
</div>

Animal.Web/Views/AnimalType/DifferentKindsOfAnimalsList.cshtml
@{
    @model  IEnumerable<Animal.Common.Models.Bal.AnimalKindModel>
        }

    <div class="form-text">
        <h2>Different Kinds Of Animals List</h2>
        @using (Html.BeginForm("AddNewAnimalKind", "AnimalType", "Get"))
        {

            <table width="90%">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PlannedNumberOfAnimals)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CurrentNumberOfAnimals)
                    </th>
                    <th>
                    @Html.DisplayNameFor(model => model.DescriptionOFAnimals)
                        <th>
                    <label>Actions</label>      
                            </th>
                </tr>
                @foreach (var animalKind in Model)
                {
                    <tr>
                        <td>
                            @*@Html.DisplayFor(modelItem => animalKind.Name)*@
                            @Html.ActionLink(animalKind.Name, "GetByAnimalType", "AnimalParticular", new {Id = animalKind.Id}, null) |
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => animalKind.PlannedNumberOfAnimals)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => animalKind.CurrentNumberOfAnimals)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => animalKind.DescriptionOFAnimals)
                        </td>
                        <td>
                            @Html.ActionLink("Update", "Update", new {id = animalKind.Id}) |
                            @Html.ActionLink("Delete", "DeleteKind", new {id = animalKind.Id})
                        </td>
                    </tr>
                }
            </table>
            <br>
            <button type="submit" class="btn btn-primary btn-large btn-block">Add new kind</button>
        }
    </div>

Animal.Web/Views/AnimalType/UpdateInformationAboutKind.cshtml
@model Animal.Common.Models.Bal.AnimalKindModel

@{
    ViewBag.Title = "UpdateInformationAboutKind";
}


<div class ="form-text">
<h2>UpdateInformationAboutKind</h2>

@using (Html.BeginForm("UpdateAnimalKind", "AnimalType", "Post"))
{
    <div class="change-form">
        @Html.LabelFor(x => x.Name)
        @Html.TextBoxFor(x => x.Name)
        @Html.ValidationMessageFor(x => x.Name)
        <br>
        @Html.LabelFor(x => x.PlannedNumberOfAnimals)
        @Html.TextBoxFor(x => x.PlannedNumberOfAnimals)
        @Html.ValidationMessageFor(x => x.PlannedNumberOfAnimals)
        <br>
        @Html.LabelFor(x => x.DescriptionOFAnimals)
        @Html.TextBoxFor(x => x.DescriptionOFAnimals)
        @Html.ValidationMessageFor(x => x.DescriptionOFAnimals)
        <br>
        <button type="submit" value="btn btn-primary btn-large btn-block">Update</button>
     
    </div>
}
    </div>

Animal.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class ="form-text">
<h2>@ViewBag.Title.</h2>

<h2>Welcome, dear visitor!</h2>
<h4>We are glad to see you here</h4>


<p id ="description_about_service">As you know, farming is one of the indispensable branches in our life.
    People use everything connected with farming
    Moreover, in our time animals become closer to people than before: a clear example of this is the acquisition of various copies
    This service is designed to interact with animals, to collect statistics about their well-being.
    No animal can get injured with using our service
    <br>
    Animal husbandry is the branch of agriculture concerned with animals that are raised for meat, fibre, milk, eggs, or other products. It includes day-to-day care, selective breeding and the raising of livestock.
    <br>
    Husbandry has a long history, starting with the Neolithic revolution when animals were first domesticated, from around 13,000 BC onwards, antedating farming of the first crops. By the time of early civilisations such as ancient Egypt, cattle, sheep, goats and pigs were being raised on farms.
    <br>
    Major changes took place in the Columbian Exchange when Old World livestock were brought to the New World, and then in the British Agricultural Revolution of the 18th century, when livestock breeds like the Dishley Longhorn cattle and Lincoln Longwool sheep were rapidly improved by agriculturalists such as Robert Bakewell to yield more meat, milk, and wool.
    <br>
    A wide range of other species such as horse, water buffalo, llama, rabbit and guinea pig are used as livestock in some parts of the world. Aquaculture of fish, molluscs, and crustaceans, and the keeping of bees and silkworms is widespread. Insects for human consumption are raised in several countries; for example, the production of crickets is a profitable industry in Thailand.
    <br>
    Modern animal husbandry relies on production systems adapted to the type of land available. Subsistence farming is being superseded by intensive animal farming in the more developed parts of the world, where for example beef cattle are kept in high density feedlots, and thousands of chickens may be raised in broiler houses or batteries. On poorer soil such as in uplands, animals are often kept more extensively, and may be allowed to roam widely, foraging for themselves.
    <br>
    Most livestock are herbivores, except for the pig which is an omnivore. Ruminants like cattle and sheep are adapted to feed on grass; they can forage outdoors, or may be fed entirely or in part on rations richer in energy and protein, such as pelleted cereals. Pigs and poultry cannot digest the cellulose in forage, and require cereals and other high-energy foods.
    <br>
    Husbandry, especially if it is intensive, has a substantial environmental impact, occupying about a third of the earth's ice-free land, causing loss of habitat and emitting about half of all greenhouse gas worldwide. Since the 18th century, people have become increasingly concerned about the welfare of farm animals, and laws and standards are widely enforced in response. In culture, animal husbandry often has an idyllic image, featuring in children's books and songs, where happy animals live in attractive countryside. A similar image may be projected by petting farms and by historic farms that offer farm-stays to paying visitors.
    <br>
    <p align ="center"><h3>This project was created to improve your interaction with animals, so you can start using it!</h3> </p>
    </p>


<a href="@Url.Action("GetRegistrationView","Account")" >
      <button type="submit" class="btn btn-primary btn-large btn-block">Go to registration page</button>
</a>
    </div>

Animal.Web/Views/NewsBoard/AddNews.cshtml
@model Animal.Common.Models.Bal.ParticularNewsModel

@{
    ViewBag.Title = "AddNews";
}
<div class ="form-text">
<h2>Add news</h2>

@using (Html.BeginForm("AddNews", "NewsBoard", "Post"))
{

    <div class="change-form">

        @Html.LabelFor(x => x.Message)
        <br>
        @Html.TextBoxFor(x => x.Message)
        @Html.ValidationMessageFor(x => x.Message)
    <br>
    <div class="buttons-actions">
        <div class="go">
            <button type="submit" class="btn btn-primary btn-large btn-block">Add commentary</button>
        </div>
        <div class="cancel">
            <button type="reset" class="btn btn-primary btn-large btn-block">Back</button>
        </div>
    </div>
    </div >
}

    </div>

Animal.Web/Views/NewsBoard/NewsBoardPage.cshtml
@{
    ViewBag.Title = "NewsBoardPage";
    @model  IEnumerable<Animal.Common.Models.Bal.ParticularNewsModel>
  
}
    <div class ="form-text">
<h2>News board page</h2>

@using (Html.BeginForm("GetAddNews", "NewsBoard", "Get"))
{

    <table width="80%" class="commentaries-board">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Message)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>

        @foreach (var newsParticular in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => newsParticular.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => newsParticular.Message)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => newsParticular.Date)
                </td>
            </tr>
        }
    </table>

        <button type="button" class="btn btn-primary btn-large btn-block">Add new commentary</button>

}
        </div>

Animal.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>@ViewBag.Title - Animal Husbandry</title>
@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/modernizr")
    <link rel="icon" href="@Url.Content("favicon.ico")" type="image/x-icon" />
    <link rel="shortcut icon" href="@Url.Content("favicon.ico")" type="image/x-icon" />
</head>
<body>


<div class="navbar navbar-inverse navbar-fixed-top" >
<div class="container">
    <div class="navbar-header">
    </div>
    <div class="navbar-collapse collapse">

        <ul class="menu-main">
            @if (User.Identity.IsAuthenticated)
          { 
        @Html.ActionLink("Animal Husbandry:Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
       <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Сommentaries", "GetNewsBoardPageView", "NewsBoard")</li>
        <!-- <li>@Html.ActionLink("Add new kind of animal", "GetAnimalKindAddingView", "AnimalType")</li>
<li>@Html.ActionLink("Add new animal", "GetAnimalViewForAdd", "AnimalParticular")</li> -->

        <li>@Html.ActionLink("Kinds of animals", "ListOfKindsView", "AnimalType")</li>
        <li>@Html.ActionLink("Own cab", "OwnCabView", "Account")</li>
        <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
            }
            else
            {
                @Html.ActionLink("Animal Husbandry:Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <li>@Html.ActionLink("About", "About", "Home")</li>
            <li>@Html.ActionLink("Login", "GetAuthorizationView", "Account")</li>
            <li>@Html.ActionLink("Registration", "GetRegistrationView", "Account")</li>
            }
        </ul>
    </div>
</div>


<div class="container body-content">
    @RenderBody()
    <hr/>
    
    <footer id="footer">
        <p>&copy; Rastsvietalov Sergey PI-15-4 @DateTime.UtcNow - Animal Husbandry</p>
        <br>
        Email: rastsvietalovjudo@gmail.com
    </footer>
</div>


@Scripts.Render("~/bundles/jquery")
<!--@Scripts.Render("~/bundles/bootstrap") -->
@RenderSection("scripts", false)
</body>
</html>